---
- name: Deploy Docker Container
  hosts: localhost
  connection: local
  become: false

  tasks:

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Pull Docker Image
      docker_image:
        name: "vishnudholu/calculator:latest"
        source: pull

    - name: Remove existing container (if any)
      shell: docker rm -f calculator || true

    - name: Run Docker Container
      shell: docker run -d --name calculator vishnudholu/calculator:latest
