---
- name: Deploy Calculator Container
  hosts: local
  become: false

  tasks:

    - name: Pull latest Docker image
      community.docker.docker_image:
        name: vishnudholu/calculator
        tag: latest
        source: pull

    - name: Remove old container
      community.docker.docker_container:
        name: calculator
        state: absent

    - name: Run new container
      community.docker.docker_container:
        name: calculator
        image: vishnudholu/calculator:latest
        state: started
        detach: true
