---
- name: Deploy Docker Container
  hosts: localhost
  connection: local
  become: false

  tasks:
    - name: Start Docker service
      service:
        name: docker
        state: started
      become: true

    - name: Pull Docker Image
      shell: docker pull vishnudholu/calculator:latest

    - name: Remove existing container (if any)
      shell: docker rm -f calculator || true

    - name: Run Docker Container (Interactive & Detached)
      shell: docker run -dit --name calculator vishnudholu/calculator:latest
